version: '3.7'
volumes:
  kong_data: {}
  users_data: {}
networks:
  #Red interna para comunicar los servicios (“Services on the same network can communicate with each other using their name”)
  kong-net:
services:
  Vinos-API:
    image: tiendavinos-api-image
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      # Networks to join 
      - kong-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://TiendaVinos-database:3306/TiendaVinos?createDatabaseIfNotExist=true
    depends_on:
      - TiendaVinos-database

  TiendaVinos-database:
    image: mysql #Usamos imagen del respositorio ya creada
    hostname: TiendaVinos-database
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    ports:
      - "3307:3306"
    networks:
      - kong-net
    volumes:
      - users_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'TiendaVinos'
      MYSQL_ROOT_PASSWORD: 'password'
